---
title: "data_transformation"
author: "Travis Deason"
date: "2/6/2018"
output: html_document
---

```{r setup, include=FALSE}
rm( list = ls()); cat("\014")  # Clear environment
require(stringr)
require(plotly)
require(Hmisc)
require(tidyr)
require(dplyr)
require(ggplot2)
require(plyr)
require(reshape2)
source('../src/r_functions.R')
data <- read.csv('../data/train.csv')
names(data) <- sapply(names(data), tolower)
```

```{r}
bla <- c(1,2,3,4,5,6,7,8,9,10)
bla[-1]
```


```{r}
dfnan <- fill_nulls(data)
```




```{r}
dfo <- make_dummy(dfnan, sep='_',
                  known_cats = c('mssubclass'), 
                  cat_but_keep=c('fireplaces','garagecars', 'yrsold', 'fullbath', 'halfbath', 'kitchenabvgr', 'bsmtfullbath', 'bsmthalfbath',
                                 'lotfrontage_isNA', 'masvnrarea_isNA', 'garageyrblt_isNA'))
```

```{r}
write.csv(dfo, '../train_clean.csv')
```



```{r}
data2 <- read.csv('../data/test.csv')
df2_nan <- fill_nulls(data)
```

```{r}
df2 <- make_dummy(df2_nan, sep='_',
                  known_cats = c('mssubclass'), 
                  cat_but_keep=c('fireplaces','garagecars', 'yrsold', 'fullbath', 'halfbath', 'kitchenabvgr', 'bsmtfullbath', 'bsmthalfbath',
                                 'lotfrontage_isNA', 'masvnrarea_isNA', 'garageyrblt_isNA'))
```
```{r}
write.csv(df2,'../test_clean.csv')
```

